CREATE DATABASE IF NOT EXISTS BD_ALUGUEL;
USE BD_ALUGUEL;

CREATE TABLE IF NOT EXISTS CLIENTE(
CLI_ID INT AUTO_INCREMENT PRIMARY KEY,
    CLI_NOME VARCHAR(50) NOT NULL,
    CLI_CPF VARCHAR(11) NOT NULL,
    CLI_EMAIL VARCHAR(50) NOT NULL,
    CLI_TELEFONE VARCHAR(9) NOT NULL
);

ALTER TABLE CLIENTE
MODIFY COLUMN CLI_CPF VARCHAR(11) NOT NULL UNIQUE;

CREATE TABLE IF NOT EXISTS PRODUTO(
PRO_ID             INT AUTO_INCREMENT PRIMARY KEY,
    PRO_NOME           VARCHAR(50) NOT NULL,
    PRO_DESCRICAO      VARCHAR(200) NOT NULL,
    PRO_PRECO          DOUBLE NOT NULL,
    PRO_QTD_DISPONIVEL INT NOT NULL
);

CREATE TABLE IF NOT EXISTS ALUGUEL(
ALU_ID              INT AUTO_INCREMENT PRIMARY KEY,
    ALU_DATA_ALUGUEL    DATE NOT NULL,
    ALU_DATA_DEVOLUCAO  DATE NOT NULL,
    ALU_VALOR_TOTAL     DOUBLE NOT NULL,
    FK_CLI_ID           INT,
    FOREIGN KEY (FK_CLI_ID) REFERENCES CLIENTE(CLI_ID)
);

CREATE TABLE IF NOT EXISTS ALUGUEL_PRODUTO(
ALP_ID              INT AUTO_INCREMENT PRIMARY KEY,
    FK_PRO_ID    INT NOT NULL,
    FK_ALU_ID  INT NOT NULL,
    FOREIGN KEY (FK_PRO_ID) REFERENCES PRODUTO(PRO_ID),
    FOREIGN KEY (FK_ALU_ID) REFERENCES ALUGUEL(ALU_ID)
);

INSERT INTO CLIENTE ( CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES ("Davi", "12345678910", "Davi@email.com", "987654321");

INSERT INTO CLIENTE ( CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES ("Julio", "10987654321", "Julio@email.com", "123456789");

SELECT * FROM CLIENTE;

INSERT INTO PRODUTO (   PRO_NOME,
PRO_PRECO,
                        PRO_QTD_DISPONIVEL)
VALUES   ("Iphone 18 Pro Max",
589.90,
                        100);
                       
INSERT INTO PRODUTO    (PRO_NOME,
PRO_DESCRICAO,
PRO_PRECO,
                        PRO_QTD_DISPONIVEL)
VALUES   ("Lancha Turbo",
"Lancha para rio e mar",
                        2358.75,
                        5);
                       
                       
SELECT * FROM PRODUTO;

INSERT INTO ALUGUEL   ( ALU_DATA_ALUGUEL,
ALU_DATA_DEVOLUCAO,
ALU_VALOR_TOTAL,
FK_CLI_ID)
VALUES ("2026-10-08",
"2026-10-15",
                         600.89,
                         2);
                         
SELECT * FROM ALUGUEL;

INSERT INTO ALUGUEL_PRODUTO(FK_PRO_ID, FK_ALU_ID)
VALUES (1,1);

SELECT * FROM ALUGUEL_PRODUTO;

INSERT INTO CLIENTE ( CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES ("Ana Silva", "12345678900", "ana.silva@email.com", "987654321");

INSERT INTO CLIENTE ( CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES ("Bruno Souza", "23456789011", "bruno.souza@email.com", "976543210");

INSERT INTO CLIENTE ( CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES ("Carla Mendes", "34567890122", "carla.mendes@email.com", "965432109");

INSERT INTO CLIENTE ( CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES ("Daniel Rocha", "45678901233", "daniel.rocha@email.com", "954321098");

INSERT INTO CLIENTE ( CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES ("Elaine Costa", "56789012344", "elaine.costa@email.com", "943210987");

INSERT INTO CLIENTE ( CLI_NOME, CLI_CPF, CLI_EMAIL, CLI_TELEFONE)
VALUES ("Felipe Lima", "67890123455", "felipe.lima@email.com", "932109876");

SELECT * FROM CLIENTE;


INSERT INTO PRODUTO (PRO_NOME,
PRO_DESCRICAO,
PRO_PRECO,
PRO_QTD_DISPONIVEL)
VALUES       ('Notebook Dell Inspiron', 'Notebook com processador Intel Core i7, 16GB de RAM, 512GB SSD', 450.00, 10),
('Smartphone Samsung Galaxy S21', 'Smartphone com tela de 6.2 polegadas, 128GB de armazenamento', 350.00, 15),
('TV LG 55" 4K', 'Smart TV com resolução 4K e HDR', 280.00, 8),
('Drone DJI Phantom 4', 'Drone com câmera 4K e estabilização de imagem', 300.00, 55),
('Câm. Canon EOSI T7', 'Câmera DSLR com lente 18-55mm, 24.1MP', 250.00, 2),
('Câmera GoPro Hero 9', 'Câmera de ação com resolução 5K e resistência à água', 80.00, 60),
('Tenda Eventos 5x5m', 'Tenda resistente à água e fácil de montar', 200.00, 4),
('Microfone Shure SM58', 'Microfone para apresentações e shows', 40.00, 35),
('Mesa de Som Behringer', 'Mesa de som com 16 canais e efeitos integrados', 500.00, 3),
('Kit de Iluminação Fotográfica', 'Kit com softbox, tripés e lâmpadas de LED', 100.00, 6);
                     
SELECT * FROM PRODUTO;
SELECT PRO_NOME, PRO_DESCRICAO FROM PRODUTO;
SELECT PRO_NOME, PRO_DESCRICAO, PRO_PRECO FROM PRODUTO;

-- SELECIONE APENAS OS PRODUTOS COM PREÇO > 250
SELECT *
FROM PRODUTO
WHERE PRO_PRECO > 250;

-- SELECIONAR APENAS O PRODUTO DE ID =3
SELECT PRO_ID,
	   PRO_NOME
FROM   PRODUTO
WHERE PRO_ID = 3;

-- SELECIONAR TODOS OS PRODUTOS QUE CONTENHAM NOTEBOOK EM QUALQUER PARTE DO NOME
SELECT *
FROM PRODUTO
WHERE PRO_NOME LIKE "%NOTEBOOK%";

-- ATUALIZAR A QUANTIDADE DE NOTEBOOK PARA 200
UPDATE PRODUTO
SET PRO_DISPONIVEL = 200
WHERE PRO_ID = 5; -- UPDATE TEM QUE TER WHERE

-- ATUALIZAR A DESCRICAO DO NOTEBOOK PARA VAZIO
UPDATE PRODUTO
SET PRO_DESCRICAO = NULL
WHERE PRO_ID = 5; -- UPDATE TEM QUE TER WHERE

-- APAGAR (DELETAR) O NOTEBOOK 
DELETE FROM PRODUTO
WHERE PRO_ID = 5; -- DELETE TEM QUE TER WHERE



