CREATE DATABASE IF NOT EXISTS BD_GST_SUPER;
USE BD_GST_SUPER;

CREATE TABLE IF NOT EXISTS FORNECEDOR(
	CNPJ VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(9) NOT NULL
);

CREATE TABLE IF NOT EXISTS CATEGORIA(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    TIPO VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTO(
	CODIGO VARCHAR(100) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    PRECO DOUBLE NOT NULL,
    FK_ID_CATEGORIA INT(11)
);

CREATE TABLE IF NOT EXISTS FAIXA(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    FK_COD_PROD VARCHAR(100),
    FK_CNPJ_FORN VARCHAR(11)
);


    


