CREATE DATABASE IF NOT EXISTS BD_MUSICA;
USE BD_MUSICA;

CREATE TABLE IF NOT EXISTS ARTISTA(
	CPF_CNPJ VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    ENDERECO VARCHAR(9) NOT NULL
);

CREATE TABLE IF NOT EXISTS GENERO(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    ESTILO VARCHAR(10) NOT NULL,
    RITMO VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS ALBUM(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(1440),
    FK_CPF_CNPJ_ARTISTA INT,
    FOREIGN KEY (FK_CPF_CNPJ_ARTISTA) REFERENCES ALBUM(ID)
);

CREATE TABLE IF NOT EXISTS FAIXA(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CARACTERISTICAS VARCHAR(100) NOT NULL,
    FK_ID_ALBUM INT,
    FK_ID_GENERO INT,
    FOREIGN KEY (FK_ID_ALBUM) REFERENCES ALBUM(ID),
    FOREIGN KEY (FK_ID_GENERO) REFERENCES GENERO(ID)
);
    


    